#!/system/bin/sh

#深度精简模式

REPLACE="
/system/app/AnalyticsCore
/system/app/BuiltInPrintService
/system/app/BookmarkProvider
/system/app/CatchLog
/system/app/CloudPrint2
/system/app/com.google.ar.core
/system/app/Email
/system/app/FrequentPhrase
/system/app/greenguard
/system/app/GooglePrintRecommendationService
/system/app/HTMLViewer
/system/app/HybridPlatform
/system/app/HybridAccessory
/system/app/KSICibaEngine
/system/app/mab
/system/app/MiuiBugReport
/system/app/MiuiContentCatcher
/system/app/MiuiDaemon
/system/app/VoiceAssist
/system/app/MSA
/system/app/PrintSpooler
/system/app/Stk
/system/app/SecurityInputMethod
/system/app/talkback
/system/app/VoiceTrigger
/system/app/YouDaoEngine
/system/priv-app/CloudBackup
/system/priv-app/Music
/system/priv-app/MiGameCenterSDKService
/system/priv-app/MiService
/system/priv-app/MiMoverGlobal
/system/priv-app/NewHome
/system/priv-app/QuickSearchBox
/system/app/MiuiSuperMarket
/data/user/0/com.xiaomi.market​
/system/data-app/VipAccount
/system/data-app/MiShop
/system/priv-app/Browser
/data/user/0/com.android.browser
/system/app/Updater
"